spring:
  grpc:
    server:
      port: ${GRPC_SERVER_PORT:9091}
  application:
    name: delfino-world
  main:
    banner-mode: off

delfino:
  world:
    id: ${WORLD_ID:0}
    name: ${WORLD_NAME:Delfino}
    flag: ${WORLD_FLAG:0}
    messages:
      event: ${MESSAGES_EVENT:Welcome!}
      server: ${MESSAGES_SERVER:Welcome!}
      recommended: ${MESSAGES_RECOMMENDED:Welcome!}
    rates:
      exp: ${RATES_EXP:1}
      meso: ${RATES_MESO:1}
      drop: ${RATES_DROP:1}
      boss-drop: ${RATES_BOSS_DROP:1}
      quest: ${RATES_QUEST:1}
      fishing: ${RATES_FISHING:1}
      travel: ${RATES_TRAVEL:1}
    channels:
      - capacity: ${CHANNEL_1_CAPACITY:2000}
        ip: ${CHANNEL_1_IP:127.0.0.1}
        port: ${CHANNEL_1_PORT:7575}
        enabled: ${CHANNEL_1_ENABLED:true}
      - capacity: ${CHANNEL_2_CAPACITY:2000}
        ip: ${CHANNEL_2_IP:127.0.0.1}
        port: ${CHANNEL_2_PORT:7576}
        enabled: ${CHANNEL_2_ENABLED:false}
      - capacity: ${CHANNEL_3_CAPACITY:2000}
        ip: ${CHANNEL_3_IP:127.0.0.1}
        port: ${CHANNEL_3_PORT:7577}
        enabled: ${CHANNEL_3_ENABLED:false}

logging:
  level:
    root: INFO
    dev.jaczerob: DEBUG
    com.zaxxer: ERROR
    io.grpc: ERROR
  structured:
    json:
      exclude:
        - process.pid
        - ecs
        - service
        - tags