spring:
  application:
    name: Delfino
  main:
    banner-mode: off
  data:
    redis:
      database: 0
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:60000}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

delfino:
  cache:
    login: true
  mdrs:
    url: ${MDRS_HOST:0.0.0.0}:${MDRS_PORT:9090}
  world:
    url: ${WORLD_HOST:0.0.0.0}:${WORLD_PORT:9091}

server:
  port: ${SERVER_PORT:8484}

logging:
  level:
    root: INFO
    dev.jaczerob: DEBUG
    com.zaxxer: ERROR
    io.grpc: ERROR
  structured:
    json:
      exclude:
        - process.pid
        - ecs
        - service
        - tags