spring:
  application:
    name: Delfino
  main:
    banner-mode: off
  data:
    redis:
      database: 0
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:60000}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

delfino:
  world:
    id: 0
    name: 'Delfino'
    flag: 0
    messages:
      event: 'Welcome!'
      server: 'Welcome!'
      recommended: 'Welcome!'
    rates:
      exp: 1
      meso: 1
      drop: 1
      boss-drop: 1
      quest: 1
      fishing: 1
      travel: 1
    channels:
      - id: 0
        capacity: 1000
      - id: 1
        capacity: 1000
      - id: 2
        capacity: 1000
  mdrs:
    url: ${MDRS_HOST:0.0.0.0}:${MDRS_PORT:9090}

server:
  port: ${SERVER_PORT:8484}

logging:
  level:
    root: INFO
    dev.jaczerob: DEBUG
    com.zaxxer: ERROR
    io.grpc: ERROR
  structured:
    json:
      exclude:
        - process.pid
        - ecs
        - service
        - tags